# Form implementation generated from reading ui file 'aNewAltmanAug7.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(449, 193)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #121212;\n"
"color:#fff;\n"
"font:9pt \"Helvetica\";\n"
"}\n"
"\n"
"QLabel {\n"
"background:transparent;\n"
"font-size:10pt;\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"                                 QSlider\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider::groove:horizontal {\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgba(22,22,22,100);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(32, 32, 32);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(255, 88, 71);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: white;\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color:white;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QSlider\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider:vertical {\n"
"min-width:40px;\n"
"min-height:110px;\n"
"max-height:110px;\n"
"}\n"
"QSlider::groove:vertical {\n"
"border-radius: 7px;\n"
"width: 40px;\n"
"margin: 0px;\n"
"background:rgb(22, 24, 29);\n"
"}\n"
"\n"
"QSlider::groove:vertical:hover {\n"
"background: rgba(233,123,111,0.25);\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"background: rgb(233,123,111);\n"
"height: 18px;\n"
"width: 40px;\n"
"margin: 0px;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"background:transparent;\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"background-color: rgb(255,163,151);\n"
"}\n"
"\n"
"QSlider::handle:vertical:pressed {\n"
"background-color:rgb(188,78,66);\n"
"}\n"
"/* ////////////////////////////////////////////////////////////////////////////////////////////////\n"
"                                    QScrollBar\n"
"//////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background:transparent;\n"
"    height: 12px;\n"
"    margin: 0px 10px 0px 10px;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(22,22,22);\n"
"    min-width:24px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, \n"
"QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, \n"
"QScrollBar::sub-page:horizontal {\n"
"    background: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color:transparent;\n"
"    width: 12px;\n"
"    margin: 10px 0px 10px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(22,22,22);\n"
"    min-height: 12px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, \n"
"QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_12.setContentsMargins(4, 9, 4, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setStyleSheet("QTabWidget {\n"
"background-color: #fff;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;    \n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"background-color: transparent;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"background-color: transparent;\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.onepage = QtWidgets.QWidget()
        self.onepage.setObjectName("onepage")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.onepage)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setSpacing(0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.onepage)
        self.tabWidget.setStyleSheet("QTabWidget {\n"
"background-color: #fff;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;    \n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"margin-left:9px;\n"
"padding-top:2px;\n"
"padding-bottom:2px;\n"
"background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: transparent;\n"
"font-weight:bold;\n"
"font-size:8pt;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    border-radius: 4px;\n"
"    \n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"background-color: transparent;\n"
"}\n"
"")
        self.tabWidget.setIconSize(QtCore.QSize(10, 10))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_4 = QtWidgets.QFrame(parent=self.tab)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_14.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_14.setHorizontalSpacing(12)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_15 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_15.setMinimumSize(QtCore.QSize(0, 110))
        self.label_15.setStyleSheet("")
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.gridLayout_14.addWidget(self.label_15, 2, 1, 1, 1)
        self.altmans_sleep = QtWidgets.QSlider(parent=self.frame_4)
        self.altmans_sleep.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(87,111,215);}\n"
"QSlider::handle:vertical:hover {background:rgb(127,151,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(37,61,165);}\n"
"QSlider::groove:vertical:hover {background:rgba(87,111,215,0.25);}\n"
"QSlider::groove:vertical {background:rgba(87,111,215,0.15);}\n"
"\n"
"        ")
        self.altmans_sleep.setMaximum(4)
        self.altmans_sleep.setTracking(True)
        self.altmans_sleep.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_sleep.setInvertedAppearance(True)
        self.altmans_sleep.setObjectName("altmans_sleep")
        self.gridLayout_14.addWidget(self.altmans_sleep, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/basicsblue.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/outlookHole.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 2, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(parent=self.tab_2)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_20.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_20.setHorizontalSpacing(12)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_21 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_21.setMinimumSize(QtCore.QSize(0, 110))
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout_20.addWidget(self.label_21, 1, 1, 1, 1)
        self.altmans_speech = QtWidgets.QSlider(parent=self.frame_11)
        self.altmans_speech.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(68,212,146);}\n"
"QSlider::handle:vertical:hover {background:rgb(108,252,186);}\n"
"QSlider::handle:vertical:pressed {background:rgb(18,162,96);}\n"
"QSlider::groove:vertical:hover {background:rgba(68,212,146,0.25);}\n"
"\n"
"QSlider::groove:vertical {background:rgba(68,212,146,0.15);}\n"
"\n"
"        ")
        self.altmans_speech.setMaximum(4)
        self.altmans_speech.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_speech.setInvertedAppearance(True)
        self.altmans_speech.setObjectName("altmans_speech")
        self.gridLayout_20.addWidget(self.altmans_speech, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_11, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/asdfasdfasfsadfasf.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/outlookHole.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_2, icon1, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(parent=self.tab_4)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_15.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_15.setHorizontalSpacing(12)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.altmans_activity = QtWidgets.QSlider(parent=self.frame_5)
        self.altmans_activity.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(245,235,103);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,255,143);}\n"
"QSlider::handle:vertical:pressed {background:rgb(195,185,53);}\n"
"QSlider::groove:vertical:hover {background:rgba(245,235,103,0.25);}\n"
"QSlider::groove:vertical {background:rgba(245,235,103,0.15);}\n"
"        ")
        self.altmans_activity.setMaximum(4)
        self.altmans_activity.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_activity.setInvertedAppearance(True)
        self.altmans_activity.setObjectName("altmans_activity")
        self.gridLayout_15.addWidget(self.altmans_activity, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_16.setMinimumSize(QtCore.QSize(0, 110))
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.gridLayout_15.addWidget(self.label_16, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_5, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem5, 3, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/effort.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/outlookHole.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_4, icon2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem6, 2, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(parent=self.tab_3)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_21.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_21.setHorizontalSpacing(12)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.altmans_cheer = QtWidgets.QSlider(parent=self.frame_12)
        self.altmans_cheer.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(255,161,92);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,201,132);}\n"
"QSlider::handle:vertical:pressed {background:rgb(205,111,42);}\n"
"QSlider::groove:vertical:hover {background:rgba(255,161,92,0.25);}\n"
"QSlider::groove:vertical {background:rgba(255,161,92,0.15);}\n"
"\n"
"        ")
        self.altmans_cheer.setMaximum(4)
        self.altmans_cheer.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_cheer.setInvertedAppearance(True)
        self.altmans_cheer.setObjectName("altmans_cheer")
        self.gridLayout_21.addWidget(self.altmans_cheer, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_22.setMinimumSize(QtCore.QSize(0, 110))
        self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.gridLayout_21.addWidget(self.label_22, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame_12, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/asdfasfasfasfas.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/outlookHole.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_3, icon3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_7.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_7.addItem(spacerItem8, 2, 0, 1, 1)
        self.frame_13 = QtWidgets.QFrame(parent=self.tab_6)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_22.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_22.setHorizontalSpacing(12)
        self.gridLayout_22.setVerticalSpacing(0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.altmans_confidence = QtWidgets.QSlider(parent=self.frame_13)
        self.altmans_confidence.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(199,76,81);}\n"
"QSlider::handle:vertical:hover {background:rgb(239,116,121);}\n"
"QSlider::handle:vertical:pressed {background:rgb(149,26,31);}\n"
"QSlider::groove:vertical:hover {background:rgba(199,76,81,0.25);}\n"
"QSlider::groove:vertical {background:rgba(199,76,81,0.15);}\n"
"\n"
"        ")
        self.altmans_confidence.setMaximum(4)
        self.altmans_confidence.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_confidence.setInvertedAppearance(True)
        self.altmans_confidence.setObjectName("altmans_confidence")
        self.gridLayout_22.addWidget(self.altmans_confidence, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(parent=self.frame_13)
        self.label_23.setMinimumSize(QtCore.QSize(0, 110))
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout_22.addWidget(self.label_23, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.frame_13, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_7.addItem(spacerItem9, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/libidoHole.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/outlookHole.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_6, icon4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_9.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame = QtWidgets.QFrame(parent=self.tab_5)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame1 = QtWidgets.QFrame(parent=self.frame)
        self.frame1.setObjectName("frame1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_3.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame1)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 347, 166))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_8.addItem(spacerItem10, 7, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 5, 0, 1, 2)
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 2)
        self.altmans_summary_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.altmans_summary_label.setStyleSheet("font-weight:bold;margin-top:4px; margin-bottom:4px;font-size:14pt;")
        self.altmans_summary_label.setObjectName("altmans_summary_label")
        self.gridLayout_8.addWidget(self.altmans_summary_label, 1, 0, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame1, 2, 1, 1, 2)
        self.gridLayout_9.addWidget(self.frame, 1, 1, 1, 1)
        self.altmans_summary = QtWidgets.QSlider(parent=self.tab_5)
        self.altmans_summary.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(244,56,81);}\n"
"QSlider::handle:vertical:hover {background:rgb(239,116,121);}\n"
"QSlider::handle:vertical:pressed {background:rgb(149,26,31);}\n"
"QSlider::groove:vertical:hover {background:rgba(199,76,81,0.25);}\n"
"QSlider::groove:vertical {background:rgba(199,76,81,0.35);}\n"
"\n"
"        ")
        self.altmans_summary.setMaximum(20)
        self.altmans_summary.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_summary.setInvertedAppearance(True)
        self.altmans_summary.setObjectName("altmans_summary")
        self.gridLayout_9.addWidget(self.altmans_summary, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_24.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.onepage)
        self.twopage = QtWidgets.QWidget()
        self.twopage.setObjectName("twopage")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.twopage)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.altmans_manic_rating_table = QtWidgets.QTableView(parent=self.twopage)
        self.altmans_manic_rating_table.setStyleSheet("\n"
"QTableView {\n"
"background-color: transparent;\n"
"selection-background-color: #7e57c2;\n"
"gridline-color:transparent;\n"
"color: rgb(77, 15, 26);\n"
"}\n"
"QTableView::item {\n"
"padding: 1px;color: rgb(77, 15, 26);\n"
"background:rgb(229,100,111);\n"
"}\n"
"QTableView::item:selected {\n"
"    color: rgb(255, 255, 255);\n"
"background:rgb(23, 23, 23);\n"
"}\n"
"    ")
        self.altmans_manic_rating_table.setShowGrid(False)
        self.altmans_manic_rating_table.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.altmans_manic_rating_table.setSortingEnabled(True)
        self.altmans_manic_rating_table.setObjectName("altmans_manic_rating_table")
        self.altmans_manic_rating_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_25.addWidget(self.altmans_manic_rating_table, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.twopage)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.hidemeframe = QtWidgets.QFrame(parent=self.page)
        self.hidemeframe.setObjectName("hidemeframe")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.hidemeframe)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.altman_time = QtWidgets.QTimeEdit(parent=self.hidemeframe)
        self.altman_time.setObjectName("altman_time")
        self.horizontalLayout.addWidget(self.altman_time)
        self.altman_date = QtWidgets.QDateEdit(parent=self.hidemeframe)
        self.altman_date.setObjectName("altman_date")
        self.horizontalLayout.addWidget(self.altman_date)
        self.gridLayout_10.addWidget(self.hidemeframe, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.gridLayout_12.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 449, 14))
        self.menubar.setObjectName("menubar")
        self.menuBECK = QtWidgets.QMenu(parent=self.menubar)
        self.menuBECK.setObjectName("menuBECK")
        self.menuViews = QtWidgets.QMenu(parent=self.menubar)
        self.menuViews.setObjectName("menuViews")
        MainWindow.setMenuBar(self.menubar)
        self.actionCommit = QtGui.QAction(parent=MainWindow)
        self.actionCommit.setObjectName("actionCommit")
        self.actionDelete = QtGui.QAction(parent=MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionShowAltmanExam = QtGui.QAction(parent=MainWindow)
        self.actionShowAltmanExam.setObjectName("actionShowAltmanExam")
        self.actionShowAltmanTable = QtGui.QAction(parent=MainWindow)
        self.actionShowAltmanTable.setObjectName("actionShowAltmanTable")
        self.menuBECK.addAction(self.actionCommit)
        self.menuBECK.addAction(self.actionDelete)
        self.menuViews.addAction(self.actionShowAltmanExam)
        self.menuViews.addAction(self.actionShowAltmanTable)
        self.menubar.addAction(self.menuBECK.menuAction())
        self.menubar.addAction(self.menuViews.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.altmans_summary.valueChanged['int'].connect(self.altmans_summary_label.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>I did not need less sleep than usual last night.</p><p>I didn\'t need my usual 7-8 hrs of sleep and felt fine.</p><p>I slept less than 5 hours and do not feel it today.</p><p>I barely slept at all and feel horrible.</p><p>I did not sleep last night.</p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>I do not talk more than usual today.</p><p>I have noticed my rate of speaking increase today.</p><p>I have often noticed my rate of speech increase today.</p><p>My rate of speaking is consistently higher than normal.</p><p>I\'m difficult to understand and interrupt often. </p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>I am not more active (socially, sexually, work, home) than usual</p><p>I have been a little more active than usual</p><p>I am noticeably more active and for longer today</p><p>I am far more active than usual.</p><p>I am constantly active today, incapable of resting even when needing to do so.</p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Base level of cheeriness</span></p><p>Feeling happier or more cheeful than usual</p><p>Feeling happier and more cheerful, significantly.</p><p>I\'m ecstatic </p><p>I\'m annoying in my positivity. </p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Base level of confidence</span></p><p>Feeling more confident than usual today.</p><p>Feeling more confident for longer than usual today.</p><p>Confidence bordering on delusion</p><p>Delusional.</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">• A cutoff score of 6 </span>or higher indicates a high probability of a manic or hypomanic condition (based on a sensitivity rating of 85.5% and a specificity rating of 87.3%).</p><p><span style=\" font-weight:600;\">• A score of 6 </span>or higher may indicate a need for treatment and/or further diagnostic workup to confirm a diagnosis of mania or hypomania.</p><p><span style=\" font-weight:600;\">• A score of 5</span> or lower is less likely to be associated with significant symptoms of mania.</p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">How Manic Are You?</span></p></body></html>"))
        self.altmans_summary_label.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "sum"))
        self.altman_time.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.altman_date.setDisplayFormat(_translate("MainWindow", "yyyy/mm/dd"))
        self.menuBECK.setTitle(_translate("MainWindow", "Altman"))
        self.menuViews.setTitle(_translate("MainWindow", "Views"))
        self.actionCommit.setText(_translate("MainWindow", "Commit"))
        self.actionCommit.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionDelete.setText(_translate("MainWindow", "Delete Record"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.actionShowAltmanExam.setText(_translate("MainWindow", "Input View"))
        self.actionShowAltmanExam.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.actionShowAltmanTable.setText(_translate("MainWindow", "Dataview"))
        self.actionShowAltmanTable.setShortcut(_translate("MainWindow", "Ctrl+2"))
